kind: template
metadata:
  description: A basic template for using FastAPI framework
spec:
  parameters:
    - id: service_name
      kind: string
      prompt: Name your FastAPI service
      default: my-docker-service
    - id: workspace
      kind: tfy-workspace
      prompt: Choose a workspace to deploy your service
    - id: replicas
      kind: number
      prompt: Choose a number of replicas for your service
      default: 1
    - id: port
      kind: number
      prompt: Choose a port to run your service
      default: 8080
  postInitInstruction: |

  baseBuild: base_docker.yaml
  baseComponent: base_service.yaml
  overwrites:
    Component.spec.workspace: ${parameters.workspace}
    Component.spec.name: ${parameters.service_name}
    Component.spec.traits.scale.replicas: ${parameters.replicas}
    Component.spec.container.ports:
      - containerPort: ${parameters.port}
        protocol: TCP
  comments: |
#  To change the required cpu
#  Component.spec.container.resources.cpu.required: 0.5

#  To change the maximum cpu
#  Component.spec.container.resources.cpu.limit: 0.5

#  To change the required memory
#  Component.spec.container.resources.memory.required: 512000

#  To change the maximum memory
#  Component.spec.container.resources.memory.limit: 512000000

#  To change the number of replica
#  Component.spec.traits.scale.replicas: "${parameters.replicas}"

#  To change the port which are open from container
#  Component.spec.container.ports:
#    - containerPort: ${parameters.port}
#      protocol: TCP
