apiVersion: truefoundry.io/v1
kind: Component
spec:
  workloadType: Server
  osType: linux
  arch: amd64
  container:
    resources:
      cpu:
        required: 0.01
        limit: 0.05
      memory:
        required: 25600000
        limit: 128000000
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: TEST_ENV
      value: testValue
  traits:
    scale:
      replicas: 1
