apiVersion: truefoundry.io/v1
kind: Component
spec:
  workloadType: Server
  osType: linux
  arch: amd64
  container:
    resources:
      cpu:
        required: 2
      memory:
        required: 512000
    ports:
      containerPort: 8080
      protocol: TCP
    env:
    - name: TEST_ENV
      value: testValue
  traits:
    scale:
      replicas: 1